"""
backend/app/agents/tools/email_tools.py

Tool wrappers for email sending.
All tools are HITL — emails are never sent without explicit user approval.
"""

import asyncio
from typing import Any, Dict, Optional

from sqlalchemy.orm import Session

from app.models.user import User
from app.agents.tools.common import get_business_id_for_user


async def send_report_email(
    db: Session,
    user: User,
    report_type: str,
    recipient_email: Optional[str] = None,
    period_start: Optional[str] = None,
    period_end: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Generate a report and email it to the specified recipient.
    HITL — requires approval before sending.
    """
    business_id = await asyncio.to_thread(get_business_id_for_user, db, user)
    if not business_id:
        return {"error": "No business found for user"}

    # Default recipient to the user's own email
    to_email = recipient_email or user.email
    if not to_email:
        return {"error": "No recipient email provided and user has no email on file"}

    try:
        from app.services.email_service import EmailService

        email_svc = EmailService()

        subject = f"BizPilot Report: {report_type.replace('_', ' ').title()}"
        period_info = ""
        if period_start and period_end:
            period_info = f" for {period_start} to {period_end}"

        body = (
            f"Hi,\n\n"
            f"Please find your {report_type.replace('_', ' ')} report{period_info} attached.\n\n"
            f"This report was generated by BizPilot AI on your request.\n\n"
            f"Regards,\nBizPilot AI Assistant"
        )

        await asyncio.to_thread(
            email_svc.send_email,
            to_email=to_email,
            subject=subject,
            body_text=body,
        )

        return {
            "sent": True,
            "to": to_email,
            "subject": subject,
            "report_type": report_type,
            "message": f"Report email sent successfully to {to_email}",
        }
    except Exception as e:
        return {"error": f"Failed to send email: {str(e)}"}


async def send_invoice_email(
    db: Session,
    user: User,
    invoice_id: str,
    recipient_email: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Email an invoice to a customer.
    HITL — requires approval before sending.
    """
    business_id = await asyncio.to_thread(get_business_id_for_user, db, user)
    if not business_id:
        return {"error": "No business found for user"}

    try:
        from app.services.invoice_service import InvoiceService
        from app.services.email_service import EmailService

        inv_svc = InvoiceService(db)
        invoice = await asyncio.to_thread(inv_svc.get_invoice, invoice_id, business_id)
        if not invoice:
            return {"error": f"Invoice '{invoice_id}' not found"}

        to_email = recipient_email
        if not to_email and hasattr(invoice, 'customer') and invoice.customer:
            to_email = invoice.customer.email
        if not to_email:
            to_email = user.email

        email_svc = EmailService()
        subject = f"Invoice {invoice.invoice_number} from BizPilot"
        body = (
            f"Hi,\n\n"
            f"Please find invoice {invoice.invoice_number} "
            f"for R{float(invoice.total_amount or 0):,.2f}.\n\n"
            f"Regards,\nBizPilot"
        )

        await asyncio.to_thread(
            email_svc.send_email,
            to_email=to_email,
            subject=subject,
            body_text=body,
        )

        return {
            "sent": True,
            "to": to_email,
            "invoice_number": invoice.invoice_number,
            "amount": float(invoice.total_amount or 0),
            "message": f"Invoice emailed to {to_email}",
        }
    except Exception as e:
        return {"error": f"Failed to send invoice email: {str(e)}"}


async def send_custom_email(
    db: Session,
    user: User,
    recipient_email: str,
    subject: str,
    body: str,
) -> Dict[str, Any]:
    """
    Send a custom email on behalf of the business.
    HITL — requires approval before sending.
    """
    business_id = await asyncio.to_thread(get_business_id_for_user, db, user)
    if not business_id:
        return {"error": "No business found for user"}

    try:
        from app.services.email_service import EmailService

        email_svc = EmailService()
        await asyncio.to_thread(
            email_svc.send_email,
            to_email=recipient_email,
            subject=subject,
            body_text=body,
        )

        return {
            "sent": True,
            "to": recipient_email,
            "subject": subject,
            "message": f"Email sent to {recipient_email}",
        }
    except Exception as e:
        return {"error": f"Failed to send email: {str(e)}"}
