"""
test_layby_create.py
Tests for layby creation endpoint (POST /api/v1/laybys).

Root cause fixed: the endpoint was calling
    service.create_layby(business_id=..., user_id=..., data=...)
but LaybyService.create_layby expects positional arguments
    (business_id, customer_id, items, deposit_amount, frequency, created_by).
This caused an immediate TypeError → 500 on every layby creation attempt.
"""

import pytest
from decimal import Decimal


class TestLaybyCreateEndpoint:
    """Verify the layby create endpoint is registered and schema is correct."""

    def test_create_route_registered(self):
        """POST /laybys must be a registered route."""
        from app.api.laybys import router
        post_routes = [
            r for r in router.routes
            if hasattr(r, "methods") and "POST" in r.methods
            and getattr(r, "path", "").rstrip("/").endswith("/laybys")
        ]
        assert post_routes, "POST /laybys route not found"

    def test_layby_create_schema_has_required_fields(self):
        """LaybyCreate schema must have customer_id, items, deposit_amount, payment_frequency."""
        from app.schemas.layby import LaybyCreate
        fields = LaybyCreate.model_fields
        for required_field in ("customer_id", "items", "deposit_amount", "payment_frequency"):
            assert required_field in fields, f"LaybyCreate missing field: {required_field}"

    def test_layby_item_create_schema_has_required_fields(self):
        """LaybyItemCreate must have product_id, quantity, unit_price."""
        from app.schemas.layby import LaybyItemCreate
        fields = LaybyItemCreate.model_fields
        for required_field in ("product_id", "quantity", "unit_price"):
            assert required_field in fields, f"LaybyItemCreate missing field: {required_field}"

    def test_layby_service_signature_matches_api_call(self):
        """LaybyService.create_layby must accept (business_id, customer_id, items, deposit_amount, frequency, created_by)."""
        import inspect
        from app.services.layby_service import LaybyService
        sig = inspect.signature(LaybyService.create_layby)
        params = list(sig.parameters.keys())
        for expected in ("business_id", "customer_id", "items", "deposit_amount", "frequency", "created_by"):
            assert expected in params, (
                f"LaybyService.create_layby missing param '{expected}'. "
                f"Current params: {params}"
            )

    def test_zero_deposit_detected_at_service(self):
        """The service must raise ValueError when deposit is zero (not swallow it as 500)."""
        from unittest.mock import MagicMock, patch
        from app.services.layby_service import LaybyService
        from uuid import uuid4

        db = MagicMock()
        service = LaybyService(db)

        # Config disabled → feature off error
        with patch.object(service, "_get_config", return_value=None):
            with pytest.raises((ValueError, Exception)):
                service.create_layby(
                    business_id=uuid4(),
                    customer_id=uuid4(),
                    items=[],  # empty → total = 0 → ValueError
                    deposit_amount=Decimal("0"),
                    frequency="monthly",
                    created_by=uuid4(),
                )

    def test_layby_reference_number_format(self):
        """Reference numbers generated by the service must match LB-YYYYMMDD-XXXX format."""
        from unittest.mock import MagicMock
        from uuid import uuid4
        from app.services.layby_service import LaybyService

        db = MagicMock()
        service = LaybyService(db)

        # Mock the DB query to return a 0 count (no existing reference numbers today)
        mock_query = MagicMock()
        mock_query.filter.return_value.filter.return_value.count.return_value = 0
        db.query.return_value = mock_query

        ref = service._generate_reference_number(uuid4())
        import re
        assert re.match(r"LAY-\d{8}-\d{4}", ref), f"Unexpected format: {ref}"
