# DigitalOcean App Platform Specification
# Deploy: doctl apps create --spec .do/app.yaml
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: bizpilot

# Use path-based routing to keep frontend and backend on same domain
# This fixes cookie auth issues (no cross-subdomain problems)

services:
  # FastAPI Backend API
  - name: api
    github:
      repo: BrightonDube/BizPilot2
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Starter tier (~$5/mo, covered by credits)
    
    # Route /api/* to this service
    routes:
      - path: /api
        preserve_path_prefix: true
    
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_ME_GENERATE_WITH_openssl_rand_hex_32
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: ALGORITHM
        scope: RUN_TIME
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "30"
      # Cookie settings - same domain so these are simpler
      - key: COOKIE_DOMAIN
        scope: RUN_TIME
        value: ""  # Empty = current domain only (safe default)
      - key: COOKIE_SECURE
        scope: RUN_TIME
        value: "true"
      - key: COOKIE_SAMESITE
        scope: RUN_TIME
        value: "lax"  # Lax is fine for same-domain
      # DATABASE_URL and CORS_ORIGINS set manually in dashboard

  # Next.js Frontend
  - name: web
    github:
      repo: BrightonDube/BizPilot2
      branch: main
      deploy_on_push: true
    source_dir: frontend
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Starter tier (~$5/mo, covered by credits)
    
    # Route everything else to frontend
    routes:
      - path: /
    
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      # NEXT_PUBLIC_API_URL set manually after app URL is known

# NOTE: After deployment, manually set in DO Dashboard:
# 1. DATABASE_URL - Your Neon pooled connection string
# 2. CORS_ORIGINS - ["https://your-app.ondigitalocean.app"]
# 3. NEXT_PUBLIC_API_URL - https://your-app.ondigitalocean.app/api/v1
