# DigitalOcean App Platform Specification
# Deploy: doctl apps create --spec .do/app.yaml
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: bizpilot

# Use path-based routing to keep frontend and backend on same domain
# This fixes cookie auth issues (no cross-subdomain problems)

services:
  # FastAPI Backend API
  - name: api
    github:
      repo: BrightonDube/BizPilot2
      branch: main
      deploy_on_push: true
    source_dir: .
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Starter tier (~$5/mo, covered by credits)
    
    # Route /api/* to this service
    routes:
      - path: /api
        preserve_path_prefix: true
    
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_ME_GENERATE_WITH_openssl_rand_hex_32
        # IMPORTANT: Override this value in DO Dashboard with a secure key
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: ALGORITHM
        scope: RUN_TIME
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "30"
      # Cookie settings - same domain so these are simpler
      - key: COOKIE_DOMAIN
        scope: RUN_TIME
        value: ""  # Empty = current domain only (safe default)
      - key: COOKIE_SECURE
        scope: RUN_TIME
        value: "true"
      - key: COOKIE_SAMESITE
        scope: RUN_TIME
        value: "lax"  # Lax is fine for same-domain
      # DATABASE_URL from managed PostgreSQL
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${db.DATABASE_URL}
      # CORS_ORIGINS set manually in dashboard
      # Email - set these in DO Dashboard for production email sending
      - key: EMAILS_ENABLED
        scope: RUN_TIME
        value: "false"  # Set to "true" in dashboard after configuring SMTP
      - key: SMTP_HOST
        scope: RUN_TIME
        value: ""  # Configure in dashboard
      - key: SMTP_PORT
        scope: RUN_TIME
        value: "587"
      - key: SMTP_STARTTLS
        scope: RUN_TIME
        value: "true"
      - key: SMTP_USER
        scope: RUN_TIME
        type: SECRET
        value: ""  # Configure in dashboard
      - key: SMTP_PASSWORD
        scope: RUN_TIME
        type: SECRET
        value: ""  # Configure in dashboard
      - key: EMAILS_FROM_EMAIL
        scope: RUN_TIME
        value: "noreply@bizpilotpro.app"
      - key: EMAILS_FROM_NAME
        scope: RUN_TIME
        value: "BizPilot"
      # Paystack - required for subscription payments
      - key: PAYSTACK_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: ""  # Configure in dashboard
      - key: PAYSTACK_PUBLIC_KEY
        scope: RUN_TIME
        value: ""  # Configure in dashboard
      # Frontend URL for payment callbacks
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: ""  # Set to your app URL in dashboard, e.g., https://bizpilotpro.app

  # Next.js Frontend
  - name: web
    github:
      repo: BrightonDube/BizPilot2
      branch: main
      deploy_on_push: true
    source_dir: .
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Starter tier (~$5/mo, covered by credits)
    
    # Route everything else to frontend
    routes:
      - path: /
    
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      # NEXT_PUBLIC_API_URL set manually after app URL is known
      # INTERNAL_API_URL for server-to-server communication (middleware auth checks)
      # This uses the internal service URL to avoid routing through the public ingress
      - key: INTERNAL_API_URL
        scope: RUN_TIME
        value: ${api.PRIVATE_URL}/api/v1

jobs:
  # Run Alembic migrations before deploying services.
  # This avoids running migrations in the API container startup.
  - name: release-migrate
    kind: PRE_DEPLOY
    github:
      repo: BrightonDube/BizPilot2
      branch: main
      deploy_on_push: true
    source_dir: .
    dockerfile_path: backend/Dockerfile
    run_command: python -m alembic -c alembic.ini upgrade head
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_ME_GENERATE_WITH_openssl_rand_hex_32
        # IMPORTANT: Override this value in DO Dashboard with a secure key

  # Optional: post-deploy seeding. Use with care (can be destructive depending on script).
  # Uncomment and set the command you want if you need automated seeding.
  # - name: release-seed
  #   kind: POST_DEPLOY
  #   github:
  #     repo: BrightonDube/BizPilot2
  #     branch: main
  #     deploy_on_push: false
  #   source_dir: backend
  #   dockerfile_path: Dockerfile
  #   run_command: python -m scripts.seed_production
  #   instance_count: 1
  #   instance_size_slug: apps-s-1vcpu-0.5gb
  #   envs:
  #     - key: ENVIRONMENT
  #       scope: RUN_TIME
  #       value: production

# NOTE: After deployment, manually set in DO Dashboard:
# 1. CORS_ORIGINS - ["https://your-app.ondigitalocean.app"]
# 2. NEXT_PUBLIC_API_URL - https://your-app.ondigitalocean.app/api/v1
#
# DATABASE: This spec references an existing DigitalOcean Managed Database.
# You must create the database separately and bind it to this app via the DO dashboard
# or provide the connection string as DATABASE_URL environment variable.

databases:
  # Reference an existing DigitalOcean Managed PostgreSQL database
  # Create database first: doctl databases create bizpilot-postgres --engine pg --size db-s-1vcpu-1gb --region nyc1
  - name: db
    engine: PG
    production: true
    cluster_name: bizpilot-postgres
    # The cluster must be created separately via DO dashboard or doctl
