# DigitalOcean App Platform Specification
# Deploy: doctl apps create --spec .do/app.yaml
# Docs: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: bizpilot
region: blr

features:
  - buildpack-stack=ubuntu-22

services:
  # FastAPI Backend API
  - name: api
    github:
      repo: BrightonDube/BizPilot2
      branch: dev
      deploy_on_push: true
    source_dir: .
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Starter tier (~$5/mo, covered by credits)
    
    # Health check configuration
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3
    
    envs:
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: DEBUG
        scope: RUN_TIME
        value: "false"
      - key: ALGORITHM
        scope: RUN_TIME
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        scope: RUN_TIME
        value: "30"
      - key: COOKIE_DOMAIN
        scope: RUN_TIME
        value: ""  # Empty for same-origin (recommended for security)
      - key: COOKIE_SECURE
        scope: RUN_TIME
        value: "true"
      - key: COOKIE_SAMESITE
        scope: RUN_TIME
        value: "lax"  # Allows cookies in navigation but blocks CSRF
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: '["https://bizpilot-ajp9i.ondigitalocean.app","https://bizpilotpro.app"]'
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        value: "239369796650-a89435qfs452tf7pggfj5df8vtgtved0.apps.googleusercontent.com"
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GROQ_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FRONTEND_URL
        scope: RUN_TIME
        value: "https://bizpilotpro.app"
      - key: EMAILS_ENABLED
        scope: RUN_AND_BUILD_TIME
        value: "True"
      - key: SMTP_HOST
        scope: RUN_AND_BUILD_TIME
        value: "smtp-relay.brevo.com"
      - key: SMTP_PORT
        scope: RUN_AND_BUILD_TIME
        value: "587"
      - key: SMTP_USER
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SMTP_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: SMTP_TIMEOUT
        scope: RUN_AND_BUILD_TIME
        value: "10"
      - key: SMTP_STARTTLS
        scope: RUN_AND_BUILD_TIME
        value: "True"
      - key: EMAILS_FROM_EMAIL
        scope: RUN_TIME
        value: "noreply@bizpilotpro.app"
      - key: EMAILS_FROM_NAME
        scope: RUN_TIME
        value: "BizPilot"
      - key: PAYSTACK_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: PAYSTACK_PUBLIC_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: BIZPILOT_SUPERADMIN_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET

  # Next.js Frontend
  - name: web
    github:
      repo: BrightonDube/BizPilot2
      branch: dev
      deploy_on_push: true
    source_dir: .
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb  # Starter tier (~$5/mo, covered by credits)
    
    envs:
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: NEXT_PUBLIC_API_URL
        scope: BUILD_TIME
        value: "/api/v1"
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_TIME
        value: "/api/v1"
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        scope: BUILD_TIME
        value: "239369796650-a89435qfs452tf7pggfj5df8vtgtved0.apps.googleusercontent.com"
      - key: NEXT_PUBLIC_GOOGLE_CLIENT_ID
        scope: RUN_TIME
        value: "239369796650-a89435qfs452tf7pggfj5df8vtgtved0.apps.googleusercontent.com"
      - key: INTERNAL_API_URL
        scope: RUN_TIME
        value: "http://api:8000/api/v1"

jobs:
  # Run Alembic migrations before deploying services.
  # This avoids running migrations in the API container startup.
  - name: release-migrate
    kind: PRE_DEPLOY
    github:
      repo: BrightonDube/BizPilot2
      branch: dev
      deploy_on_push: true
    source_dir: .
    dockerfile_path: backend/Dockerfile
    run_command: python -m alembic -c alembic.ini upgrade head
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    envs:
      - key: ENVIRONMENT
        scope: RUN_TIME
        value: production
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
        # This will use the value set in the DigitalOcean dashboard
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        # This will use the value set in the DigitalOcean dashboard

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: api
        preserve_path_prefix: true
    - match:
        path:
          prefix: /
      component:
        name: web

domains:
  - domain: bizpilotpro.app
    type: PRIMARY
    zone: bizpilotpro.app
