"""Modifier and combo analytics service.

Provides aggregate queries for reporting dashboards — modifier
selection frequency, revenue contribution, combo performance,
and modifier popularity rankings (Requirement 10).

All queries operate on the order_item_modifiers table (denormalised
price snapshots) so results are accurate even if modifier prices
change after the order was placed.

Why a separate analytics service instead of adding to AddonService?
Analytics queries are read-only, involve aggregate SQL, and serve
a different audience (managers/owners) than the CRUD operations.
Keeping them separate prevents the CRUD service from becoming
bloated and makes it easy to add caching or materialised views
later without touching the operational code.
"""

from datetime import date, datetime
from decimal import Decimal
from typing import Any, Dict, List, Optional, Tuple

from sqlalchemy import func, desc, asc, case, and_
from sqlalchemy.orm import Session

from app.models.combo import ComboDeal
from app.models.order import Order, OrderItem
from app.models.order_item_modifier import OrderItemModifier


class ModifierAnalyticsService:
    """Read-only analytics for modifier and combo reporting."""

    def __init__(self, db: Session):
        self.db = db

    # ── Modifier Selection Frequency ─────────────────────────────

    def get_modifier_selection_frequency(
        self,
        business_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
        location_id: Optional[str] = None,
        product_id: Optional[str] = None,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        """Get how often each modifier is selected, ordered by popularity.

        Returns:
            List of dicts with modifier_name, group_name, selection_count.
        """
        query = (
            self.db.query(
                OrderItemModifier.modifier_name,
                OrderItemModifier.group_name,
                func.count(OrderItemModifier.id).label("selection_count"),
            )
            .join(OrderItem, OrderItem.id == OrderItemModifier.order_item_id)
            .join(Order, Order.id == OrderItem.order_id)
            .filter(
                Order.business_id == business_id,
                OrderItemModifier.deleted_at.is_(None),
            )
        )

        query = self._apply_date_filters(query, start_date, end_date)

        if product_id:
            query = query.filter(OrderItem.product_id == product_id)

        results = (
            query
            .group_by(OrderItemModifier.modifier_name, OrderItemModifier.group_name)
            .order_by(desc("selection_count"))
            .limit(limit)
            .all()
        )

        return [
            {
                "modifier_name": row.modifier_name,
                "group_name": row.group_name,
                "selection_count": row.selection_count,
            }
            for row in results
        ]

    # ── Modifier Revenue ─────────────────────────────────────────

    def get_modifier_revenue(
        self,
        business_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        """Get revenue generated by each modifier.

        Uses the total_price snapshot from order_item_modifiers for
        historical accuracy.

        Returns:
            List of dicts with modifier_name, total_revenue, selection_count.
        """
        query = (
            self.db.query(
                OrderItemModifier.modifier_name,
                OrderItemModifier.group_name,
                func.sum(OrderItemModifier.total_price).label("total_revenue"),
                func.count(OrderItemModifier.id).label("selection_count"),
            )
            .join(OrderItem, OrderItem.id == OrderItemModifier.order_item_id)
            .join(Order, Order.id == OrderItem.order_id)
            .filter(
                Order.business_id == business_id,
                OrderItemModifier.deleted_at.is_(None),
            )
        )

        query = self._apply_date_filters(query, start_date, end_date)

        results = (
            query
            .group_by(OrderItemModifier.modifier_name, OrderItemModifier.group_name)
            .order_by(desc("total_revenue"))
            .limit(limit)
            .all()
        )

        return [
            {
                "modifier_name": row.modifier_name,
                "group_name": row.group_name,
                "total_revenue": float(row.total_revenue or 0),
                "selection_count": row.selection_count,
            }
            for row in results
        ]

    # ── Combo Analytics ──────────────────────────────────────────

    def get_combo_performance(
        self,
        business_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
        limit: int = 20,
    ) -> List[Dict[str, Any]]:
        """Get combo deal sales metrics.

        Queries the combo_deals table joined with order data to show
        how many times each combo was sold and total savings given.

        Note: This requires combo_deal_id on OrderItem. If not yet
        linked, falls back to combo_deals table metadata only.
        """
        # Return combo deal stats from the deals table itself
        # (full order integration requires combo_deal_id on OrderItem)
        combos = (
            self.db.query(ComboDeal)
            .filter(
                ComboDeal.business_id == business_id,
                ComboDeal.deleted_at.is_(None),
            )
            .order_by(ComboDeal.sort_order.asc())
            .limit(limit)
            .all()
        )

        return [
            {
                "combo_id": str(combo.id),
                "name": combo.display_name,
                "combo_price": float(combo.combo_price),
                "original_price": float(combo.original_price),
                "savings_per_combo": float(
                    Decimal(str(combo.original_price)) - Decimal(str(combo.combo_price))
                ),
                "is_active": combo.is_active,
            }
            for combo in combos
        ]

    # ── Modifier Rankings ────────────────────────────────────────

    def get_modifier_rankings(
        self,
        business_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
        order_by: str = "popular",
        limit: int = 10,
    ) -> List[Dict[str, Any]]:
        """Get ranked list of modifiers by popularity or revenue.

        Args:
            order_by: 'popular' (most selected), 'unpopular' (least),
                      'revenue' (highest revenue), 'aov_impact' (AOV lift).
        """
        query = (
            self.db.query(
                OrderItemModifier.modifier_name,
                OrderItemModifier.group_name,
                func.count(OrderItemModifier.id).label("selection_count"),
                func.sum(OrderItemModifier.total_price).label("total_revenue"),
                func.avg(OrderItemModifier.total_price).label("avg_price"),
            )
            .join(OrderItem, OrderItem.id == OrderItemModifier.order_item_id)
            .join(Order, Order.id == OrderItem.order_id)
            .filter(
                Order.business_id == business_id,
                OrderItemModifier.deleted_at.is_(None),
            )
        )

        query = self._apply_date_filters(query, start_date, end_date)

        query = query.group_by(
            OrderItemModifier.modifier_name, OrderItemModifier.group_name
        )

        if order_by == "unpopular":
            query = query.order_by(asc("selection_count"))
        elif order_by == "revenue":
            query = query.order_by(desc("total_revenue"))
        else:  # 'popular' or 'aov_impact'
            query = query.order_by(desc("selection_count"))

        results = query.limit(limit).all()

        return [
            {
                "modifier_name": row.modifier_name,
                "group_name": row.group_name,
                "selection_count": row.selection_count,
                "total_revenue": float(row.total_revenue or 0),
                "avg_price": float(row.avg_price or 0),
                "rank": idx + 1,
            }
            for idx, row in enumerate(results)
        ]

    # ── Summary Stats ────────────────────────────────────────────

    def get_modifier_summary(
        self,
        business_id: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> Dict[str, Any]:
        """Get high-level modifier statistics for the dashboard.

        Returns total modifier selections, total modifier revenue,
        and the percentage of orders that include at least one modifier.
        """
        # Total modifier count and revenue
        base_query = (
            self.db.query(
                func.count(OrderItemModifier.id).label("total_selections"),
                func.coalesce(func.sum(OrderItemModifier.total_price), 0).label(
                    "total_revenue"
                ),
            )
            .join(OrderItem, OrderItem.id == OrderItemModifier.order_item_id)
            .join(Order, Order.id == OrderItem.order_id)
            .filter(
                Order.business_id == business_id,
                OrderItemModifier.deleted_at.is_(None),
            )
        )
        base_query = self._apply_date_filters(base_query, start_date, end_date)
        totals = base_query.first()

        # Orders with at least one modifier
        orders_with_mods = (
            self.db.query(func.count(func.distinct(Order.id)))
            .join(OrderItem, OrderItem.order_id == Order.id)
            .join(OrderItemModifier, OrderItemModifier.order_item_id == OrderItem.id)
            .filter(
                Order.business_id == business_id,
                OrderItemModifier.deleted_at.is_(None),
            )
        )
        orders_with_mods = self._apply_date_filters(orders_with_mods, start_date, end_date)
        modifier_order_count = orders_with_mods.scalar() or 0

        # Total orders in period
        total_orders_query = (
            self.db.query(func.count(Order.id))
            .filter(Order.business_id == business_id)
        )
        total_orders_query = self._apply_date_filters(total_orders_query, start_date, end_date)
        total_orders = total_orders_query.scalar() or 0

        modifier_adoption_rate = (
            (modifier_order_count / total_orders * 100) if total_orders > 0 else 0
        )

        return {
            "total_selections": totals.total_selections if totals else 0,
            "total_revenue": float(totals.total_revenue if totals else 0),
            "orders_with_modifiers": modifier_order_count,
            "total_orders": total_orders,
            "modifier_adoption_rate": round(modifier_adoption_rate, 1),
        }

    # ── Private Helpers ──────────────────────────────────────────

    def _apply_date_filters(self, query, start_date, end_date):
        """Apply optional date range filters to an order-based query."""
        if start_date:
            query = query.filter(Order.created_at >= datetime.combine(start_date, datetime.min.time()))
        if end_date:
            query = query.filter(Order.created_at <= datetime.combine(end_date, datetime.max.time()))
        return query
