"""sync_schema_with_models

Revision ID: 4777487a7c3d
Revises: 029_add_stock_reservations
Create Date: 2026-01-17 12:37:37.872804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4777487a7c3d'
down_revision: Union[str, None] = '029_add_stock_reservations'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_stock_reservations_layby'), table_name='stock_reservations')
    op.drop_index(op.f('idx_stock_reservations_location'), table_name='stock_reservations')
    op.drop_index(op.f('idx_stock_reservations_product'), table_name='stock_reservations')
    op.drop_index(op.f('idx_stock_reservations_status'), table_name='stock_reservations')
    op.drop_table('stock_reservations')
    op.drop_index(op.f('ix_business_users_department_id'), table_name='business_users')
    op.add_column('departments', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_departments_business_id'), table_name='departments')
    op.drop_constraint(op.f('uq_departments_business_name'), 'departments', type_='unique')
    op.alter_column('favorite_products', 'auto_reorder',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('favorite_products', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('favorite_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('favorite_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('favorite_products', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_favorite_products_unique'), table_name='favorite_products', postgresql_where='(deleted_at IS NULL)')
    op.drop_constraint(op.f('favorite_products_product_id_fkey'), 'favorite_products', type_='foreignkey')
    op.drop_constraint(op.f('favorite_products_business_id_fkey'), 'favorite_products', type_='foreignkey')
    op.drop_constraint(op.f('favorite_products_user_id_fkey'), 'favorite_products', type_='foreignkey')
    op.create_foreign_key(None, 'favorite_products', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'favorite_products', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(None, 'favorite_products', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_invoices_paystack_reference'), table_name='invoices')
    op.create_index(op.f('ix_invoices_payment_reference'), 'invoices', ['payment_reference'], unique=False)
    op.drop_column('invoices', 'paystack_access_code')
    op.drop_column('invoices', 'gateway_fee')
    op.drop_column('invoices', 'paystack_reference')
    op.drop_column('invoices', 'gateway_fee_percent')
    op.alter_column('job_execution_logs', 'invoices_processed',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_execution_logs', 'notifications_created',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_execution_logs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_execution_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('job_execution_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('job_execution_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('layby_audit', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('layby_audit', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_layby_audit_created'), table_name='layby_audit')
    op.drop_index(op.f('idx_layby_audit_layby'), table_name='layby_audit')
    op.create_index(op.f('ix_layby_audit_layby_id'), 'layby_audit', ['layby_id'], unique=False)
    op.add_column('layby_config', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('layby_items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('layby_items', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('layby_notifications', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('layby_notifications', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('layby_notifications', 'channel',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('email', 'sms', 'push', 'in_app', name='notificationchannel'),
               existing_nullable=False)
    op.alter_column('layby_notifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'sent', 'failed', 'cancelled', name='notificationstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('layby_notifications', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_layby_notifications_created'), table_name='layby_notifications')
    op.drop_index(op.f('idx_layby_notifications_layby'), table_name='layby_notifications')
    op.drop_index(op.f('idx_layby_notifications_status'), table_name='layby_notifications')
    op.drop_index(op.f('idx_layby_notifications_type'), table_name='layby_notifications')
    op.create_index(op.f('ix_layby_notifications_layby_id'), 'layby_notifications', ['layby_id'], unique=False)
    op.create_index(op.f('ix_layby_notifications_notification_type'), 'layby_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_layby_notifications_status'), 'layby_notifications', ['status'], unique=False)
    op.alter_column('layby_payments', 'payment_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('deposit', 'installment', 'final', 'overpayment', name='laybypaymenttype'),
               existing_nullable=False)
    op.alter_column('layby_payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'completed', 'failed', 'refunded', name='laybypaymentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.drop_index(op.f('idx_layby_payments_layby'), table_name='layby_payments')
    op.create_index(op.f('ix_layby_payments_layby_id'), 'layby_payments', ['layby_id'], unique=False)
    op.alter_column('layby_schedules', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'partial', 'paid', 'overdue', name='schedulestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('idx_layby_schedules_due'), table_name='layby_schedules')
    op.drop_index(op.f('idx_layby_schedules_layby'), table_name='layby_schedules')
    op.create_index(op.f('ix_layby_schedules_due_date'), 'layby_schedules', ['due_date'], unique=False)
    op.create_index(op.f('ix_layby_schedules_layby_id'), 'layby_schedules', ['layby_id'], unique=False)
    op.add_column('laybys', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('laybys', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('draft', 'active', 'ready_for_collection', 'completed', 'cancelled', 'overdue', name='laybystatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('laybys', 'payment_frequency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('weekly', 'bi_weekly', 'monthly', name='paymentfrequency'),
               existing_nullable=False)
    op.drop_index(op.f('ix_laybys_business_customer'), table_name='laybys')
    op.drop_index(op.f('ix_laybys_business_status'), table_name='laybys')
    op.drop_index(op.f('ix_laybys_next_payment_date'), table_name='laybys')
    op.drop_constraint(op.f('laybys_reference_number_key'), 'laybys', type_='unique')
    op.drop_index(op.f('ix_laybys_reference_number'), table_name='laybys')
    op.create_index(op.f('ix_laybys_reference_number'), 'laybys', ['reference_number'], unique=True)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_business_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.alter_column('pos_connections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('pos_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('pos_connections', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_pos_connections_provider'), table_name='pos_connections')
    op.alter_column('pos_sync_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('pos_sync_logs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('pos_sync_logs', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('product_suppliers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('product_suppliers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('product_suppliers', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('production_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'in_progress', 'completed', 'cancelled', name='productionstatus'),
               nullable=True,
               existing_server_default=sa.text("'draft'::productionstatus"))
    op.alter_column('production_orders', 'scheduled_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('production_orders', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('production_orders', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('production_orders', 'estimated_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('production_orders', 'actual_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_production_orders_status'), table_name='production_orders')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.create_unique_constraint(None, 'sessions', ['refresh_token_hash'])
    op.alter_column('time_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('time_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('time_entries', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_time_entries_clock_in'), table_name='time_entries')
    op.alter_column('users', 'biometric_public_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ux_users_single_superadmin_true'), table_name='users', postgresql_where='(is_superadmin = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_users_single_superadmin_true'), 'users', ['is_superadmin'], unique=True, postgresql_where='(is_superadmin = true)')
    op.alter_column('users', 'biometric_public_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ix_time_entries_clock_in'), 'time_entries', ['clock_in'], unique=False)
    op.alter_column('time_entries', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('time_entries', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('time_entries', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_production_orders_status'), 'production_orders', ['status'], unique=False)
    op.alter_column('production_orders', 'actual_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('production_orders', 'estimated_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('production_orders', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('production_orders', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('production_orders', 'scheduled_date',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('production_orders', 'status',
               existing_type=postgresql.ENUM('draft', 'pending', 'in_progress', 'completed', 'cancelled', name='productionstatus'),
               nullable=False,
               existing_server_default=sa.text("'draft'::productionstatus"))
    op.alter_column('product_suppliers', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('product_suppliers', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('product_suppliers', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('pos_sync_logs', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('pos_sync_logs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pos_sync_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_pos_connections_provider'), 'pos_connections', ['provider'], unique=False)
    op.alter_column('pos_connections', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('pos_connections', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pos_connections', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_business_id_fkey'), 'notifications', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.alter_column('notifications', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('notifications', 'is_archived',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_laybys_reference_number'), table_name='laybys')
    op.create_index(op.f('ix_laybys_reference_number'), 'laybys', ['reference_number'], unique=False)
    op.create_unique_constraint(op.f('laybys_reference_number_key'), 'laybys', ['reference_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_laybys_next_payment_date'), 'laybys', ['next_payment_date'], unique=False)
    op.create_index(op.f('ix_laybys_business_status'), 'laybys', ['business_id', 'status'], unique=False)
    op.create_index(op.f('ix_laybys_business_customer'), 'laybys', ['business_id', 'customer_id'], unique=False)
    op.alter_column('laybys', 'payment_frequency',
               existing_type=sa.Enum('weekly', 'bi_weekly', 'monthly', name='paymentfrequency'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('laybys', 'status',
               existing_type=sa.Enum('draft', 'active', 'ready_for_collection', 'completed', 'cancelled', 'overdue', name='laybystatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('laybys', 'deleted_at')
    op.drop_index(op.f('ix_layby_schedules_layby_id'), table_name='layby_schedules')
    op.drop_index(op.f('ix_layby_schedules_due_date'), table_name='layby_schedules')
    op.create_index(op.f('idx_layby_schedules_layby'), 'layby_schedules', ['layby_id'], unique=False)
    op.create_index(op.f('idx_layby_schedules_due'), 'layby_schedules', ['due_date'], unique=False)
    op.alter_column('layby_schedules', 'status',
               existing_type=sa.Enum('pending', 'partial', 'paid', 'overdue', name='schedulestatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_layby_payments_layby_id'), table_name='layby_payments')
    op.create_index(op.f('idx_layby_payments_layby'), 'layby_payments', ['layby_id'], unique=False)
    op.alter_column('layby_payments', 'status',
               existing_type=sa.Enum('pending', 'completed', 'failed', 'refunded', name='laybypaymentstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'completed'::character varying"))
    op.alter_column('layby_payments', 'payment_type',
               existing_type=sa.Enum('deposit', 'installment', 'final', 'overpayment', name='laybypaymenttype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_layby_notifications_status'), table_name='layby_notifications')
    op.drop_index(op.f('ix_layby_notifications_notification_type'), table_name='layby_notifications')
    op.drop_index(op.f('ix_layby_notifications_layby_id'), table_name='layby_notifications')
    op.create_index(op.f('idx_layby_notifications_type'), 'layby_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('idx_layby_notifications_status'), 'layby_notifications', ['status'], unique=False)
    op.create_index(op.f('idx_layby_notifications_layby'), 'layby_notifications', ['layby_id'], unique=False)
    op.create_index(op.f('idx_layby_notifications_created'), 'layby_notifications', ['created_at'], unique=False)
    op.alter_column('layby_notifications', 'sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('layby_notifications', 'status',
               existing_type=sa.Enum('pending', 'sent', 'failed', 'cancelled', name='notificationstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('layby_notifications', 'channel',
               existing_type=sa.Enum('email', 'sms', 'push', 'in_app', name='notificationchannel'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('layby_notifications', 'deleted_at')
    op.drop_column('layby_notifications', 'updated_at')
    op.drop_column('layby_items', 'deleted_at')
    op.drop_column('layby_items', 'updated_at')
    op.drop_column('layby_config', 'deleted_at')
    op.drop_index(op.f('ix_layby_audit_layby_id'), table_name='layby_audit')
    op.create_index(op.f('idx_layby_audit_layby'), 'layby_audit', ['layby_id'], unique=False)
    op.create_index(op.f('idx_layby_audit_created'), 'layby_audit', ['created_at'], unique=False)
    op.drop_column('layby_audit', 'deleted_at')
    op.drop_column('layby_audit', 'updated_at')
    op.alter_column('job_execution_logs', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('job_execution_logs', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('job_execution_logs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('job_execution_logs', 'error_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_execution_logs', 'notifications_created',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_execution_logs', 'invoices_processed',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('invoices', sa.Column('gateway_fee_percent', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('1.5'), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('paystack_reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('gateway_fee', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('paystack_access_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_invoices_payment_reference'), table_name='invoices')
    op.create_index(op.f('ix_invoices_paystack_reference'), 'invoices', ['paystack_reference'], unique=False)
    op.drop_constraint(None, 'favorite_products', type_='foreignkey')
    op.drop_constraint(None, 'favorite_products', type_='foreignkey')
    op.drop_constraint(None, 'favorite_products', type_='foreignkey')
    op.create_foreign_key(op.f('favorite_products_user_id_fkey'), 'favorite_products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('favorite_products_business_id_fkey'), 'favorite_products', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('favorite_products_product_id_fkey'), 'favorite_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_favorite_products_unique'), 'favorite_products', ['business_id', 'product_id', 'user_id'], unique=True, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('favorite_products', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('favorite_products', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('favorite_products', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('favorite_products', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('favorite_products', 'auto_reorder',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_unique_constraint(op.f('uq_departments_business_name'), 'departments', ['business_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_departments_business_id'), 'departments', ['business_id'], unique=False)
    op.alter_column('departments', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('departments', 'deleted_at')
    op.create_index(op.f('ix_business_users_department_id'), 'business_users', ['department_id'], unique=False)
    op.create_table('stock_reservations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('layby_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'reserved'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reserved_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('released_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['layby_id'], ['laybys.id'], name=op.f('stock_reservations_layby_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('stock_reservations_product_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_reservations_pkey')),
    sa.UniqueConstraint('layby_id', 'product_id', 'location_id', name=op.f('uq_stock_reservation_layby_product_location'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_stock_reservations_status'), 'stock_reservations', ['status'], unique=False)
    op.create_index(op.f('idx_stock_reservations_product'), 'stock_reservations', ['product_id'], unique=False)
    op.create_index(op.f('idx_stock_reservations_location'), 'stock_reservations', ['location_id'], unique=False)
    op.create_index(op.f('idx_stock_reservations_layby'), 'stock_reservations', ['layby_id'], unique=False)
    # ### end Alembic commands ###
