"""sync_schema_with_current_state

Revision ID: 6e181364b886
Revises: ef3bb807b7d5
Create Date: 2026-01-19 01:19:54.423560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e181364b886'
down_revision: Union[str, None] = 'ef3bb807b7d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Safely drop business_time_settings table only if it's empty
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT COUNT(*) FROM business_time_settings"))
    row_count = result.scalar()
    
    if row_count == 0:
        print("Dropping empty business_time_settings table")
        op.drop_table('business_time_settings')
    else:
        print(f"Skipping drop of business_time_settings table - contains {row_count} rows")
    
    # Update timestamp columns to use timezone-aware DateTime
    op.alter_column('departments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('layby_config', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('laybys', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    
    # Add indexes for stock_reservations table (if they don't exist)
    try:
        op.create_index(op.f('ix_stock_reservations_layby_id'), 'stock_reservations', ['layby_id'], unique=False)
    except Exception as e:
        print(f"Index ix_stock_reservations_layby_id already exists or error: {e}")
    
    try:
        op.create_index(op.f('ix_stock_reservations_location_id'), 'stock_reservations', ['location_id'], unique=False)
    except Exception as e:
        print(f"Index ix_stock_reservations_location_id already exists or error: {e}")
    
    try:
        op.create_index(op.f('ix_stock_reservations_product_id'), 'stock_reservations', ['product_id'], unique=False)
    except Exception as e:
        print(f"Index ix_stock_reservations_product_id already exists or error: {e}")
    
    try:
        op.create_index(op.f('ix_stock_reservations_status'), 'stock_reservations', ['status'], unique=False)
    except Exception as e:
        print(f"Index ix_stock_reservations_status already exists or error: {e}")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_reservations_status'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_product_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_location_id'), table_name='stock_reservations')
    op.drop_index(op.f('ix_stock_reservations_layby_id'), table_name='stock_reservations')
    op.alter_column('laybys', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('layby_config', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('departments', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('business_time_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('business_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day_end_time', postgresql.TIME(), server_default=sa.text("'23:59:00'::time without time zone"), autoincrement=False, nullable=False),
    sa.Column('auto_clock_out_penalty_hours', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('5.00'), autoincrement=False, nullable=True),
    sa.Column('standard_work_hours', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('8.00'), autoincrement=False, nullable=True),
    sa.Column('overtime_threshold', sa.NUMERIC(precision=4, scale=2), server_default=sa.text('8.00'), autoincrement=False, nullable=True),
    sa.Column('payroll_period_type', sa.VARCHAR(length=20), server_default=sa.text("'monthly'::character varying"), autoincrement=False, nullable=True),
    sa.Column('payroll_period_start_day', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('business_time_settings_business_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('business_time_settings_pkey')),
    sa.UniqueConstraint('business_id', name=op.f('business_time_settings_business_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
